# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='save_pwd',
            field=models.BooleanField(default=None, verbose_name='记住密码'),
        ),
    ]
