# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-14 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210614_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='save_pwd',
        ),
    ]
