# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-15 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_save_pwd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='articletotag',
            options={'verbose_name_plural': '文章标签第三张表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': '站点表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name_plural': '点赞点踩表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_read',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号码'),
        ),
    ]
